In [1]:
import numpy as np
x = np.arange(1, 25).reshape(12, 2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [2]:
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [5]:
x_train

array([[23, 24],
       [ 3,  4],
       [ 1,  2],
       [21, 22],
       [19, 20],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10],
       [15, 16]])

In [6]:
x_test

array([[11, 12],
       [13, 14],
       [17, 18]])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y)
x_train

array([[19, 20],
       [21, 22],
       [ 9, 10],
       [ 7,  8],
       [ 5,  6],
       [13, 14],
       [17, 18],
       [23, 24],
       [ 1,  2]])

In [8]:
x_test

array([[ 3,  4],
       [11, 12],
       [15, 16]])

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, shuffle=False)
x_train

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [25]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [26]:
numpy.random.shuffle(x)
training, test = x[:10,:], x[10:,:]

In [27]:
training

array([[ 7,  8],
       [17, 18],
       [ 9, 10],
       [ 3,  4],
       [23, 24],
       [ 5,  6],
       [ 1,  2],
       [21, 22],
       [15, 16],
       [11, 12]])

In [28]:
test

array([[19, 20],
       [13, 14]])

In [29]:
training, validation, test = x[:8,:], x[8:10,:], x[10:,:]

In [30]:
training

array([[ 7,  8],
       [17, 18],
       [ 9, 10],
       [ 3,  4],
       [23, 24],
       [ 5,  6],
       [ 1,  2],
       [21, 22]])

In [31]:
validation

array([[15, 16],
       [11, 12]])

In [32]:
test

array([[19, 20],
       [13, 14]])

In [33]:
x

array([[ 7,  8],
       [17, 18],
       [ 9, 10],
       [ 3,  4],
       [23, 24],
       [ 5,  6],
       [ 1,  2],
       [21, 22],
       [15, 16],
       [11, 12],
       [19, 20],
       [13, 14]])

In [34]:
indices = numpy.random.permutation(x.shape[0])
indices

array([ 3,  8,  9, 11,  2,  5,  7,  6,  4,  0,  1, 10])

In [35]:
training_idx, test_idx = indices[:10], indices[10:]
training, test = x[training_idx,:], x[test_idx,:]

In [36]:
training

array([[ 3,  4],
       [15, 16],
       [11, 12],
       [13, 14],
       [ 9, 10],
       [ 5,  6],
       [21, 22],
       [ 1,  2],
       [23, 24],
       [ 7,  8]])

In [37]:
test

array([[17, 18],
       [19, 20]])

In [40]:
x

array([[ 7,  8],
       [17, 18],
       [ 9, 10],
       [ 3,  4],
       [23, 24],
       [ 5,  6],
       [ 1,  2],
       [21, 22],
       [15, 16],
       [11, 12],
       [19, 20],
       [13, 14]])

In [41]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [39]:
from sklearn.model_selection import StratifiedKFold

In [47]:
skf = StratifiedKFold(n_splits=5)
skf.get_n_splits(x, y)

5

In [49]:
for train_index, test_index in skf.split(x,y):
    
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 2  4  5  6  7  8  9 10 11] TEST: [0 1 3]
TRAIN: [ 0  1  3  6  7  8  9 10 11] TEST: [2 4 5]
TRAIN: [ 0  1  2  3  4  5  8  9 10 11] TEST: [6 7]
TRAIN: [ 0  1  2  3  4  5  6  7 10 11] TEST: [8 9]
TRAIN: [0 1 2 3 4 5 6 7 8 9] TEST: [10 11]
